/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Employee_Phones;
import campany.Campany;
import campany.Tools;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class frmEmployee extends javax.swing.JFrame {

    /**
     * Creates new form frmEmployee
     */
    public frmEmployee() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        btngroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtempname = new controls.JTextBox(15);
        txtaddress = new controls.JTextBox(15);
        txtsalary = new controls.JTextBox(15);
        txthiringdate = new com.toedter.calendar.JDateChooser();
        txtbirthdate = new com.toedter.calendar.JDateChooser();
        cbxdept = new controls.JMyCombBox();
        btnadd = new controls.JMyButton();
        btnupdate = new controls.JMyButton();
        btndelete = new controls.JMyButton();
        btnfind = new controls.JMyButton();
        btnall = new controls.JMyButton();
        btnclear = new controls.JMyButton();
        btnback = new controls.JMyButton();
        jLabel9 = new javax.swing.JLabel();
        rdonumber = new javax.swing.JRadioButton();
        rdoname = new javax.swing.JRadioButton();
        rdoaddress = new javax.swing.JRadioButton();
        rdohiringdate = new javax.swing.JRadioButton();
        rdobirthdate = new javax.swing.JRadioButton();
        rdodept = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtempno = new controls.JTextBox(15);
        txtsearch = new controls.JTextBox(15);
        btnsearch = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnadddept = new controls.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblphone = new javax.swing.JTable();
        txtphone = new controls.JTextBox(15);
        jLabel10 = new javax.swing.JLabel();
        btnaddphone = new controls.JMyButton();
        btnremove = new controls.JMyButton();
        jSeparator3 = new javax.swing.JSeparator();
        rdosalary = new javax.swing.JRadioButton();
        rdoPhone = new javax.swing.JRadioButton();
        btndel = new controls.JMyButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Employee Form");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setText("Number:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setText("Salary:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setText("Hiring Date:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel7.setText("Birth Date:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel8.setText("Department:");

        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupdateMouseExited(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeleteMouseExited(evt);
            }
        });
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfind.setText("Find");
        btnfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfindMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfindMouseExited(evt);
            }
        });
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnall.setText("All");
        btnall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnallMouseExited(evt);
            }
        });
        btnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel9.setText("Search By:");

        rdonumber.setBackground(new java.awt.Color(255, 255, 255));
        rdonumber.setSelected(true);
        rdonumber.setText("Number");

        rdoname.setBackground(new java.awt.Color(255, 255, 255));
        rdoname.setText("Name");

        rdoaddress.setBackground(new java.awt.Color(255, 255, 255));
        rdoaddress.setText("Address");

        rdohiringdate.setBackground(new java.awt.Color(255, 255, 255));
        rdohiringdate.setText("HiringDate");

        rdobirthdate.setBackground(new java.awt.Color(255, 255, 255));
        rdobirthdate.setText("BirthDate");

        rdodept.setBackground(new java.awt.Color(255, 255, 255));
        rdodept.setText("Department");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtempno.setEditable(false);

        btnsearch.setText("Search");
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchMouseExited(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "Salary", "Hiring Date", "Birth Date", "Dept_Number", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmp.getTableHeader().setResizingAllowed(false);
        tblEmp.getTableHeader().setReorderingAllowed(false);
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        btnadddept.setText("+");
        btnadddept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadddeptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadddeptMouseExited(evt);
            }
        });
        btnadddept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddeptActionPerformed(evt);
            }
        });

        tblphone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblphone.getTableHeader().setResizingAllowed(false);
        tblphone.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblphone);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel10.setText("Phone:");

        btnaddphone.setText("Add");
        btnaddphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddphoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddphoneMouseExited(evt);
            }
        });
        btnaddphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddphoneActionPerformed(evt);
            }
        });

        btnremove.setText("Remove");
        btnremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnremoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnremoveMouseExited(evt);
            }
        });
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        rdosalary.setBackground(new java.awt.Color(255, 255, 255));
        rdosalary.setText("Salary");

        rdoPhone.setBackground(new java.awt.Color(255, 255, 255));
        rdoPhone.setText("Phone");

        btndel.setText("Del");
        btndel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndelMouseExited(evt);
            }
        });
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel11.setText("(1980 - 1999)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)
                                .addComponent(txthiringdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(txtbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(23, 23, 23)
                                .addComponent(cbxdept, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnadddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(65, 65, 65)
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnaddphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(btndel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                    .addComponent(btnremove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(52, 52, 52)
                                    .addComponent(txtaddress))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(64, 64, 64)
                                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnall, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addComponent(txtempno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(rdonumber)
                        .addGap(17, 17, 17)
                        .addComponent(rdoname)
                        .addGap(17, 17, 17)
                        .addComponent(rdoaddress)
                        .addGap(18, 18, 18)
                        .addComponent(rdohiringdate)
                        .addGap(18, 18, 18)
                        .addComponent(rdobirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(rdodept)
                        .addGap(18, 18, 18)
                        .addComponent(rdosalary)
                        .addGap(18, 18, 18)
                        .addComponent(rdoPhone)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtempno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rdonumber))
                    .addComponent(rdoname)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoaddress)
                        .addComponent(rdohiringdate)
                        .addComponent(rdobirthdate)
                        .addComponent(rdodept)
                        .addComponent(rdosalary)
                        .addComponent(rdoPhone)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txthiringdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnadddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cbxdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnaddphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setValues(){
        emp.setAddress(txtaddress.getText());
        emp.setEmpNo(Integer.parseInt(txtempno.getText()));
        emp.setEmpName(txtempname.getText());
        emp.setSalary(Double.parseDouble(txtsalary.getText()));
        String DName = cbxdept.getSelectedItem().toString();
        String DNo= dept.getValueByName(DName);
        emp.setDeptNo(Integer.parseInt(DNo));
        
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String hDate = String.valueOf(f.format(txthiringdate.getDate()));
        String BDate = String.valueOf(f.format(txtbirthdate.getDate()));
        emp.setBirthDate(BDate);
        emp.setHiringDate(hDate);
    }
    
    Employee_Phones Phones = new Employee_Phones();
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if (txtempno.getText().equals("") || txtempname.getText().equals("") || txtaddress.getText().equals("") || txtsalary.getText().equals("") || txthiringdate.getDate()==null || txtbirthdate.getDate() == null || cbxdept.getSelectedItem()==null){
        Tools.msgBox("The information is not Completed...");
        }
        else{
        Date d =new Date();
        SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
        String s ="1999-12-31";
        String s2 = "1980-01-01";
        int BD = Integer.parseInt(format.format(txtbirthdate.getDate()).substring(0, 4));
        int HD = Integer.parseInt(format.format(txthiringdate.getDate()).substring(0, 4));
        Date dnow = new Date();
        Date d2 =new Date();
        Date d3 = new Date();
        try {
            d= format.parse(s);
            dnow=format.parse(format.format(d2));
            d3 = format.parse(s2);
        } catch (ParseException ex) {
            Tools.msgBox(ex.getMessage());
        }
           
            if (txtempname.getText().matches("[a-zA-Z|\\s]+")){
               if (txtempno.getText().matches("[0-9]+")&& txtempno.getText().charAt(0)!= '0'){
                   if (txtaddress.getText().matches("[a-zA-Z|\\s]+")){
                       if (txtsalary.getText().matches("[0-9]+[.][0-9]+") || txtsalary.getText().matches("[0-9]+")){
                           if(!txtbirthdate.getDate().after(d) && !txtbirthdate.getDate().before(d3)){
                               if (!txthiringdate.getDate().after(dnow) || format.format(txthiringdate.getDate()).equals(format.format(dnow))){
                                    if (HD-BD >= 20){
                                    DefaultTableModel model = (DefaultTableModel)tblphone.getModel();
                                    setValues();
                                    emp.add();
                                    Phones.setEmpNo(Integer.parseInt(txtempno.getText()));
                                    for (int x=0 ; x < tblphone.getRowCount() ; x++){
                                        Phones.setPhone(tblphone.getValueAt(x, 0).toString());
                                        Phones.add();
                                    }
                                    model.setNumRows(0);
                                    clearData();
                                    emp.getAllRows(tblEmp);
                                    }
                                    else{
                                      Tools.msgBox("The Age of employment must be at least 20 years...");
                                    }
                               }
                               else{
                                   Tools.msgBox("Hiring Date must be before today or today...");
                               }
                           }
                           else{
                             Tools.msgBox("Date Of Birth must be Max (1999) And Min (1980)");  
                           }
                       }
                       else{
                           Tools.msgBox("The Salary is wrong...");
                       }
                   }else{
                       Tools.msgBox("Address must be letters only...");
                   }
               }
                 else{
                    Tools.msgBox("The Number must be numbers only except zero in the first digit...");   
                 }
               }
               else{
                  Tools.msgBox("The Name must be letters only..."); 
               }

            }

        
    }//GEN-LAST:event_btnaddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btngroup.add(rdonumber);
        btngroup.add(rdoname);
        btngroup.add(rdoaddress);
        btngroup.add(rdosalary);
        btngroup.add(rdobirthdate);
        btngroup.add(rdohiringdate);
        btngroup.add(rdodept);
        btngroup.add(rdoPhone);
        db.go.fillComb("department", "deptname", cbxdept);
        
        emp.getAllRows(tblEmp);
        clearData();
    }//GEN-LAST:event_formWindowOpened

    Department dept = new Department();
    Employee emp = new Employee();
    
    private void btnadddeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddeptActionPerformed
        // TODO add your handling code here:
        int DeptNo = Integer.parseInt(dept.getAutoNumber());
        String DeptName = (String)Tools.InputBox("Enter Department Name:");
        String Location = (String)Tools.InputBox("Enter Location:");
        if (DeptName != null && Location != null){
            if (DeptName.matches("[a-zA-Z][0-9|a-zA-Z|\\s]+")){
                if (Location.matches("[a-zA-Z]+")){
                    dept.setDeptNo(DeptNo);
                    dept.setDeptName(DeptName);
                    dept.setLocation(Location);
                    dept.add();
                    db.go.fillComb("department", "deptname", cbxdept);
                }
                else{
                   Tools.msgBox("Location must be Letters only..."); 
                }
            }
            else{
                Tools.msgBox("Department Name must be numbers or Letters only but no number in the first digit...");
            }
        }
        else {
            Tools.msgBox("No Department Is Added...");
        } 
    }//GEN-LAST:event_btnadddeptActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new frmMain());
    }//GEN-LAST:event_btnbackActionPerformed

    private void clearData(){
        Tools.clearText(this);
        txtempno.setText(emp.getAutoNumber());
        btnadd.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btnremoveActionPerformed(null);
        txtempname.requestFocus();
    }
    
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        if (txtempno.getText().equals("") || txtempname.getText().equals("") || txtaddress.getText().equals("") || txtsalary.getText().equals("") || txthiringdate.getDate()==null || txtbirthdate.getDate() == null || cbxdept.getSelectedItem()==null){
        Tools.msgBox("The information is not Completed...");
        }
        else{
            Date d =new Date();
        SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
        String s ="1999-12-31";
        String s2 = "1980-01-01";
        Date dnow = new Date();
        Date d2 =new Date();
        Date d3 = new Date();
        try {
            d= format.parse(s);
            dnow=format.parse(format.format(d2));
            d3 = format.parse(s2);
        } catch (ParseException ex) {
            Tools.msgBox(ex.getMessage());
        }
           if (txtempname.getText().matches("[a-zA-Z|\\s]+")){
               if (txtempno.getText().matches("[0-9]+") && txtempno.getText().charAt(0)!= '0'){
                   if (txtaddress.getText().matches("[a-zA-Z|\\s]+")){
                       if (txtsalary.getText().matches("[0-9]+[.][0-9]+") || txtsalary.getText().matches("[0-9]+")){
                           if(!txtbirthdate.getDate().after(d) && !txtbirthdate.getDate().before(d3)){
                               if (!txthiringdate.getDate().after(dnow) || format.format(txthiringdate.getDate()).equals(format.format(dnow))){
                                    setValues();
                                    emp.update();
                                    Phones.setEmpNo(Integer.parseInt(txtempno.getText()));
                                    Phones.deleteByEmp();
                                    for (int x=0 ; x < tblphone.getRowCount() ; x++){
                                        Phones.setPhone(tblphone.getValueAt(x, 0).toString());
                                        Phones.add();
                                    }
                                    clearData();
                                    emp.getAllRows(tblEmp);
                                    
                               }
                               else{
                                   Tools.msgBox("Hiring Date must be before today or today...");
                               }
                           }
                           else{
                             Tools.msgBox("Date Of Birth must be Max (1999) And Min (1980)");  
                           }
                       }
                       else{
                           Tools.msgBox("The Salary is wrong...");
                       }
                   }else{
                       Tools.msgBox("Address must be letters only...");
                   }
               }
                 else{
                    Tools.msgBox("The Number must be numbers only except zero in the first digit...");   
                 }
               }
               else{
                  Tools.msgBox("The Name must be letters only..."); 
               }
            }   
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (Tools.confirmMsg("Do you want to delete?")){
        Phones.setEmpNo(Integer.parseInt(txtempno.getText()));
        Phones.deleteByEmp();
        setValues();
        emp.delete();
        clearData();
        emp.getAllRows(tblEmp);
        
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        String strEmpNo = (String)Tools.InputBox("Enter Employee Number:");
        if (strEmpNo != null){
            if (strEmpNo.matches("[0-9]+")){
               int EmpNo = Integer.parseInt(strEmpNo);
                emp.setEmpNo(EmpNo);
                emp.getOneRow(tblEmp); 
            }
            else{
                Tools.msgBox("Employee number must be numbers only...");
            }
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallActionPerformed
        // TODO add your handling code here:
        emp.getAllRows(tblEmp);
    }//GEN-LAST:event_btnallActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        try {
            // TODO add your handling code here:
            int row = tblEmp.getSelectedRow();
            String strEmpNo = tblEmp.getValueAt(row, 0).toString();
            String strEmpName = tblEmp.getValueAt(row, 1).toString();
            String address = tblEmp.getValueAt(row, 2).toString();
            String Salary = tblEmp.getValueAt(row, 3).toString();
            String HiringDate = tblEmp.getValueAt(row, 4).toString();
            String BirthDate = tblEmp.getValueAt(row, 5).toString();
            String DeptName = tblEmp.getValueAt(row, 7).toString();
            
            txtempno.setText(strEmpNo);
            txtempname.setText(strEmpName);
            txtaddress.setText(address);
            txtsalary.setText(Salary);
            DateFormat format =new SimpleDateFormat("yyyy-MM-dd");
            Date Hd = format.parse(HiringDate);
            Date Bd = format.parse(BirthDate);
            txthiringdate.setDate(Hd);
            txtbirthdate.setDate(Bd);
            cbxdept.setSelectedItem(DeptName);
            
            Phones.setEmpNo(Integer.parseInt(txtempno.getText()));
            Phones.getAllRows(tblphone);
            
            btnadd.setEnabled(false);
            btnupdate.setEnabled(true);
            btndelete.setEnabled(true);
            
        } catch (Exception ex) {
            Tools.msgBox(ex.getMessage());
        }

        
    }//GEN-LAST:event_tblEmpMouseClicked

    private String getMyLike(){
        return " like '%"+txtsearch.getText()+"%'";
    }
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
         String strSearch = "select * from employee_data where ";
         boolean check = false ;
        if (txtsearch.getText().equals("")){
           Tools.msgBox("The Search Text is empty..."); 
        }
        else{
         if (rdoaddress.isSelected()){
             if (txtsearch.getText().matches("[a-zA-Z]+")){
                 strSearch+= "Address"+ getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text must be letters only...");
             }
         }
         else if (rdoname.isSelected()) {
             if (txtsearch.getText().matches("[a-zA-Z]+")){
                 strSearch+= "Name" + getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text must be letters only...");
             }
         }
         else if (rdonumber.isSelected()) {
             if (txtsearch.getText().matches("[0-9]+")){
                 strSearch+= "Number" + getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text must be numbers only...");
             }
         }
         else if (rdobirthdate.isSelected()) {
             if (txtsearch.getText().matches("[0-9|-]+")){
                 strSearch+= "Date_Of_Birth"+ getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text contain numbers Or special character (-) only...");
             }
         }
         else if (rdohiringdate.isSelected()) {
             if (txtsearch.getText().matches("[0-9|-]+")){
                 strSearch+= "Hiring_Date"+ getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text contain numbers Or special character (-) only...");
             }
         }
         else if (rdodept.isSelected()) {
             if (txtsearch.getText().matches("[0-9|a-zA-Z]+")){
                 strSearch+= "department_no"+ getMyLike() + " or department " + getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text contain numbers or letters only...");
             }
         }
         else if (rdosalary.isSelected()) {
             if (txtsearch.getText().matches("[0-9]+[.][0-9]+") || txtsearch.getText().matches("[0-9]+")){
                 strSearch+= "Salary"+ getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text contain positive real numbers only...");
             }
         }
         else  {
             if (txtsearch.getText().matches("[0][1][2|1|0|5]\\d{8}")){
                 String strEmpNum = Phones.getEmpNoByPhone(txtsearch.getText());
                 strSearch+= "Number like '%"+ strEmpNum + "%'";
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text invalid...");
             }
         }
         
         if (check == true){
              emp.getCustomRows(strSearch, tblEmp);  
             }

        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnaddphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddphoneActionPerformed
        // TODO add your handling code here:
        if (txtphone.getText().matches("[0][1][2|1|0|5]\\d{8}")){
            if (db.go.IsPhoneExist(txtphone.getText())){
                Tools.msgBox("This Phone Is Exist...");
                txtphone.setText("");
                txtphone.requestFocus();
            }
            else{
            DefaultTableModel model = (DefaultTableModel)tblphone.getModel();
            model.addRow(new Object[]{txtphone.getText()});
            txtphone.setText("");
            txtphone.requestFocus();
            }
        }
             else {
                 Tools.msgBox("The phone invalid....");
                 txtphone.setText("");
                 txtphone.requestFocus();
             }
        
    }//GEN-LAST:event_btnaddphoneActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblphone.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblphone.getModel();
        int a=tblphone.getSelectedRow();
        model.removeRow(a);
    }//GEN-LAST:event_btndelActionPerformed

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        // TODO add your handling code here:
        this.btnadd.setSize(95,35);
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        // TODO add your handling code here:
        this.btnadd.setSize(82, 26);
    }//GEN-LAST:event_btnaddMouseExited

    private void btnupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseEntered
        // TODO add your handling code here:
        this.btnupdate.setSize(95,35);
    }//GEN-LAST:event_btnupdateMouseEntered

    private void btnupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseExited
        // TODO add your handling code here:
        this.btnupdate.setSize(82, 26);
    }//GEN-LAST:event_btnupdateMouseExited

    private void btndeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseEntered
        // TODO add your handling code here:
        this.btndelete.setSize(95,35);
    }//GEN-LAST:event_btndeleteMouseEntered

    private void btndeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseExited
        // TODO add your handling code here:
        this.btndelete.setSize(82, 26);
    }//GEN-LAST:event_btndeleteMouseExited

    private void btnfindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseEntered
        // TODO add your handling code here:
        this.btnfind.setSize(95,35);
    }//GEN-LAST:event_btnfindMouseEntered

    private void btnfindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseExited
        // TODO add your handling code here:
        this.btnfind.setSize(82, 26);
    }//GEN-LAST:event_btnfindMouseExited

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
        // TODO add your handling code here:
        this.btnclear.setSize(95,35);
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        // TODO add your handling code here:
        this.btnclear.setSize(82, 26);
    }//GEN-LAST:event_btnclearMouseExited

    private void btnallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnallMouseEntered
        // TODO add your handling code here:
        this.btnall.setSize(95,35);
    }//GEN-LAST:event_btnallMouseEntered

    private void btnallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnallMouseExited
        // TODO add your handling code here:
        this.btnall.setSize(82, 26);
    }//GEN-LAST:event_btnallMouseExited

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        // TODO add your handling code here:
        this.btnback.setSize(95,35);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        // TODO add your handling code here:
        this.btnback.setSize(82, 26);
    }//GEN-LAST:event_btnbackMouseExited

    private void btnsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseEntered
        // TODO add your handling code here:
        this.btnsearch.setSize(115,35);
    }//GEN-LAST:event_btnsearchMouseEntered

    private void btnsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseExited
        // TODO add your handling code here:
        this.btnsearch.setSize(102,26);
    }//GEN-LAST:event_btnsearchMouseExited

    private void btnadddeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddeptMouseExited
        // TODO add your handling code here:
        this.btnadddept.setSize(41,26);
    }//GEN-LAST:event_btnadddeptMouseExited

    private void btnadddeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddeptMouseEntered
        // TODO add your handling code here:
        this.btnadddept.setSize(60,30);
    }//GEN-LAST:event_btnadddeptMouseEntered

    private void btnaddphoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddphoneMouseEntered
        // TODO add your handling code here:
        this.btnaddphone.setSize(70,30);
    }//GEN-LAST:event_btnaddphoneMouseEntered

    private void btnaddphoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddphoneMouseExited
        // TODO add your handling code here:
        this.btnaddphone.setSize(56,26);
    }//GEN-LAST:event_btnaddphoneMouseExited

    private void btndelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndelMouseEntered
        // TODO add your handling code here:
        this.btndel.setSize(70,30);
    }//GEN-LAST:event_btndelMouseEntered

    private void btndelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndelMouseExited
        // TODO add your handling code here:
        this.btndel.setSize(52,26);
    }//GEN-LAST:event_btndelMouseExited

    private void btnremoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremoveMouseEntered
        // TODO add your handling code here:
        this.btnremove.setSize(150,35);
    }//GEN-LAST:event_btnremoveMouseEntered

    private void btnremoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremoveMouseExited
        // TODO add your handling code here:
        this.btnremove.setSize(135,26);
    }//GEN-LAST:event_btnremoveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnadd;
    private controls.JMyButton btnadddept;
    private controls.JMyButton btnaddphone;
    private controls.JMyButton btnall;
    private controls.JMyButton btnback;
    private controls.JMyButton btnclear;
    private controls.JMyButton btndel;
    private controls.JMyButton btndelete;
    private controls.JMyButton btnfind;
    private javax.swing.ButtonGroup btngroup;
    private controls.JMyButton btnremove;
    private controls.JMyButton btnsearch;
    private controls.JMyButton btnupdate;
    private controls.JMyCombBox cbxdept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rdoPhone;
    private javax.swing.JRadioButton rdoaddress;
    private javax.swing.JRadioButton rdobirthdate;
    private javax.swing.JRadioButton rdodept;
    private javax.swing.JRadioButton rdohiringdate;
    private javax.swing.JRadioButton rdoname;
    private javax.swing.JRadioButton rdonumber;
    private javax.swing.JRadioButton rdosalary;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblphone;
    private javax.swing.JTextField txtaddress;
    private com.toedter.calendar.JDateChooser txtbirthdate;
    private javax.swing.JTextField txtempname;
    private javax.swing.JTextField txtempno;
    private com.toedter.calendar.JDateChooser txthiringdate;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
