/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Project;
import campany.Tools;

/**
 *
 * @author hp
 */
public class FrmProject extends javax.swing.JFrame {

    /**
     * Creates new form FrmProject
     */
    public FrmProject() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtprojectno = new controls.JTextBox(15);
        txtprojectname = new controls.JTextBox(15);
        txtlocation = new controls.JTextBox(15);
        cbxdept = new controls.JMyCombBox();
        btnadd = new controls.JMyButton();
        btnupdate = new controls.JMyButton();
        btndelete = new controls.JMyButton();
        btnfind = new controls.JMyButton();
        btnall = new controls.JMyButton();
        btnclear = new controls.JMyButton();
        btnback = new controls.JMyButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        rdodept = new javax.swing.JRadioButton();
        rdonumber = new javax.swing.JRadioButton();
        rdoname = new javax.swing.JRadioButton();
        rdolocation = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproj = new javax.swing.JTable();
        txtsearch = new controls.JTextBox(15);
        btnsearch = new controls.JMyButton();
        btnadddept = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Project Form");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setText("Project No:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("Project Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel4.setText("Location:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setText("Department:");

        txtprojectno.setEditable(false);
        txtprojectno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprojectnoActionPerformed(evt);
            }
        });

        txtprojectname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprojectnameActionPerformed(evt);
            }
        });

        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });

        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupdateMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnupdateMouseReleased(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeleteMouseExited(evt);
            }
        });
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfind.setText("Find");
        btnfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfindMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfindMouseExited(evt);
            }
        });
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnall.setText("All");
        btnall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnallMouseExited(evt);
            }
        });
        btnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setText("Search By:");

        rdodept.setBackground(new java.awt.Color(255, 255, 255));
        rdodept.setText("Department");

        rdonumber.setBackground(new java.awt.Color(255, 255, 255));
        rdonumber.setSelected(true);
        rdonumber.setText("Number");

        rdoname.setBackground(new java.awt.Color(255, 255, 255));
        rdoname.setText("Name");

        rdolocation.setBackground(new java.awt.Color(255, 255, 255));
        rdolocation.setText("Location");

        tblproj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Location", "Dept_Number", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblproj.getTableHeader().setResizingAllowed(false);
        tblproj.getTableHeader().setReorderingAllowed(false);
        tblproj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprojMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproj);

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchMouseExited(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnadddept.setText("+");
        btnadddept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadddeptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadddeptMouseExited(evt);
            }
        });
        btnadddept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddeptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(txtprojectno, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6)
                        .addGap(40, 40, 40)
                        .addComponent(rdonumber)
                        .addGap(39, 39, 39)
                        .addComponent(rdoname)
                        .addGap(45, 45, 45)
                        .addComponent(rdolocation)
                        .addGap(38, 38, 38)
                        .addComponent(rdodept))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txtprojectname, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(61, 61, 61)
                                .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(cbxdept, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnadddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtprojectno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rdonumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rdoname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdolocation)
                            .addComponent(rdodept))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtprojectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnadddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprojectnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprojectnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprojectnoActionPerformed

    private void txtprojectnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprojectnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprojectnameActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        // TODO add your handling code here:
        this.btnadd.setSize(95,35);
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        // TODO add your handling code here:
        this.btnadd.setSize(83, 27);
    }//GEN-LAST:event_btnaddMouseExited

    private void setValues(){
        pro.setProjectNo(Integer.parseInt(txtprojectno.getText()));
        pro.setProjectName(txtprojectname.getText());
        pro.setLocation(txtlocation.getText());
        int deptno = Integer.parseInt(dept.getValueByName(cbxdept.getSelectedItem().toString()));
        pro.setDeptNo(deptno);
    }
    
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        if(txtprojectno.getText().equals("") || txtprojectname.getText().equals("") || txtlocation.getText().equals("") || cbxdept.getSelectedItem()==null){
          Tools.msgBox("The information is not Completed...");
        }
        else{
            if (txtprojectno.getText().matches("[0-9]+") && txtprojectno.getText().charAt(0)!= '0'){
                if(txtprojectname.getText().matches("[a-zA-Z][0-9|a-zA-Z|\\s]+")){
                    if (txtlocation.getText().matches("[a-zA-Z]+")){
                        setValues();
                        pro.add();
                        clearData();
                        pro.getAllRows(tblproj);
                    }
                    else{
                      Tools.msgBox("Location must be Letters only...");  
                    }
                }
                else{
                 Tools.msgBox("Project Name must be numbers or Letters only but no number in the first digit...");   
                }
            }
            else{
                Tools.msgBox("Project Number must be numbers only except zero in the first digit...");
            }
        }    
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseEntered
        // TODO add your handling code here:
        this.btnupdate.setSize(95,35);

    }//GEN-LAST:event_btnupdateMouseEntered

    private void btnupdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseExited
        // TODO add your handling code here:
        this.btnupdate.setSize(83, 27);
    }//GEN-LAST:event_btnupdateMouseExited

    private void btnupdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_btnupdateMouseReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       
        if(txtprojectno.getText().equals("") || txtprojectname.getText().equals("") || txtlocation.getText().equals("") || cbxdept.getSelectedItem()==null){
          Tools.msgBox("The information is not Completed...");
        }
        else{
            if (txtprojectno.getText().matches("[0-9]+") && txtprojectno.getText().charAt(0)!= '0'){
                if(txtprojectname.getText().matches("[a-zA-Z][0-9|a-zA-Z|\\s]+")){
                    if (txtlocation.getText().matches("[a-zA-Z]+")){
                        setValues();
                        pro.update();
                        clearData();
                        pro.getAllRows(tblproj);
                    }
                    else{
                      Tools.msgBox("Location must be Letters only...");  
                    }
                }
                else{
                 Tools.msgBox("Project Name must be numbers or Letters only but no number in the first digit...");   
                }
            }
            else{
                Tools.msgBox("Project Number must be numbers only except zero in the first digit...");
            }
        }   
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseEntered
        // TODO add your handling code here:
        this.btndelete.setSize(95,35);
    }//GEN-LAST:event_btndeleteMouseEntered

    private void btndeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseExited
        // TODO add your handling code here:
        this.btndelete.setSize(83, 27);
    }//GEN-LAST:event_btndeleteMouseExited

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if (Tools.confirmMsg("Do you want to delete?")){
            setValues();
            pro.delete();
            clearData();
            pro.getAllRows(tblproj);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfindMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseEntered
        // TODO add your handling code here:
        this.btnfind.setSize(95,35);
    }//GEN-LAST:event_btnfindMouseEntered

    private void btnfindMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseExited
        // TODO add your handling code here:
        this.btnfind.setSize(83, 27);
    }//GEN-LAST:event_btnfindMouseExited

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
     String strprojNo = (String)Tools.InputBox("Enter Project Number:");
        if (strprojNo != null){
            if (strprojNo.matches("[0-9]+")){
                int projNo = Integer.parseInt(strprojNo);
                pro.setProjectNo(projNo);
                pro.getOneRow(tblproj); 
            }
            else{
                Tools.msgBox("Project number must be numbers only...");
            }
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnallMouseEntered
        // TODO add your handling code here:
        this.btnall.setSize(95,35);
    }//GEN-LAST:event_btnallMouseEntered

    private void btnallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnallMouseExited
        // TODO add your handling code here:
        this.btnall.setSize(83, 27);
    }//GEN-LAST:event_btnallMouseExited

    private void btnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallActionPerformed
     pro.getAllRows(tblproj);
    }//GEN-LAST:event_btnallActionPerformed

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
        // TODO add your handling code here:
        this.btnclear.setSize(95,35);
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        // TODO add your handling code here:
        this.btnclear.setSize(83, 27);
    }//GEN-LAST:event_btnclearMouseExited

    private void clearData(){
        Tools.clearText(this);
        txtprojectno.setText(pro.getAutoNumber());
        btnadd.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        txtprojectname.requestFocus();
    }
    
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
       clearData();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        // TODO add your handling code here:
        this.btnback.setSize(95,35);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        // TODO add your handling code here:
        this.btnback.setSize(83, 27);
    }//GEN-LAST:event_btnbackMouseExited

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new frmMain());
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseEntered
        // TODO add your handling code here:
        this.btnsearch.setSize(115, 35);
    }//GEN-LAST:event_btnsearchMouseEntered

    private void btnsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseExited
        // TODO add your handling code here:
        this.btnsearch.setSize(102, 26);
    }//GEN-LAST:event_btnsearchMouseExited

    private String getMyLike(){
        return " like '%"+txtsearch.getText()+"%'";
    }
    
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String strSearch = "select * from project_data where ";
        boolean check = false;
   
          if (txtsearch.getText().equals("")){
           Tools.msgBox("The Search Text is empty..."); 
        }
        else{           
             if (rdonumber.isSelected()){
                 if (txtsearch.getText().matches("[0-9]+")){
                     strSearch+= "PROJECT_NO" + getMyLike();
                     check = true;
                 }
                 else {
                    Tools.msgBox("The Search Text must contain numbers only..."); 
                 }
             }
             else if (rdoname.isSelected())  {
                 if (txtsearch.getText().matches("[0-9|a-zA-Z]+")){
                     strSearch+= "PROJECT_NAME" + getMyLike();
                     check= true;
                 }
                 else {
                    Tools.msgBox("The Search Text must be numbers or Letters only..."); 
                 }
             }
             else if (rdodept.isSelected()) {
             if (txtsearch.getText().matches("[0-9|a-zA-Z]+")){
                 strSearch+= "DEARTMENT_NO"+ getMyLike() + "or DEPARTMENT" + getMyLike();
                 check = true;
             }
             else{
                 Tools.msgBox("The Search Text contain numbers or letters only...");
             }
         }
             else{
                 if (txtsearch.getText().matches("[a-zA-Z]+")){
                     strSearch+= "LOCATION"+ getMyLike();
                     check= true;
                 }
                 else {
                    Tools.msgBox("The Search Text must contain letters only...");
                 }
             }
             if (check == true){
               pro.getCustomRows(strSearch, tblproj);
             }
        }

        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btngroup.add(rdodept);
        btngroup.add(rdonumber);
        btngroup.add(rdolocation);
        btngroup.add(rdoname);
        db.go.fillComb("department", "deptname", cbxdept);
        pro.getAllRows(tblproj);
        clearData();
    }//GEN-LAST:event_formWindowOpened

    private void btnadddeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddeptMouseEntered
        // TODO add your handling code here:
        this.btnadddept.setSize(55,30);
    }//GEN-LAST:event_btnadddeptMouseEntered

    private void btnadddeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddeptMouseExited
        // TODO add your handling code here:
        this.btnadddept.setSize(41,26);
    }//GEN-LAST:event_btnadddeptMouseExited

    Department dept = new Department();
    Project pro = new Project();
    
    private void btnadddeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddeptActionPerformed
        // TODO add your handling code here:
        int DeptNo = Integer.parseInt(dept.getAutoNumber());
        String DeptName = (String)Tools.InputBox("Enter Department Name:");
        String Location = (String)Tools.InputBox("Enter Location:");
        if (DeptName != null && Location != null){
            if (DeptName.matches("[a-zA-Z][0-9|a-zA-Z|\\s]+")){
                if (Location.matches("[a-zA-Z]+")){
                    dept.setDeptNo(DeptNo);
                    dept.setDeptName(DeptName);
                    dept.setLocation(Location);
                    dept.add();
                    db.go.fillComb("department", "deptname", cbxdept);
                }
                else{
                   Tools.msgBox("Location must be Letters only..."); 
                }
            }
            else{
                Tools.msgBox("Department Name must be numbers or Letters only but no number in the first digit...");
            }
        }
        else {
            Tools.msgBox("No Department Is Added...");
        }
    }//GEN-LAST:event_btnadddeptActionPerformed

    private void tblprojMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprojMouseClicked
        // TODO add your handling code here:
        try{
        int row = tblproj.getSelectedRow();
        String strProjNo = tblproj.getValueAt(row, 0).toString();
        String strProjName = tblproj.getValueAt(row, 1).toString();
        String strLocation = tblproj.getValueAt(row, 2).toString();
        String strDeptName = tblproj.getValueAt(row, 4).toString();
        
        txtprojectno.setText(strProjNo);
        txtprojectname.setText(strProjName);
        txtlocation.setText(strLocation);
        cbxdept.setSelectedItem(strDeptName);
        
        btnadd.setEnabled(false);
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
    }
    catch(Exception ex){
        Tools.msgBox(ex.getMessage());
    }
    
    }//GEN-LAST:event_tblprojMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnadd;
    private controls.JMyButton btnadddept;
    private controls.JMyButton btnall;
    private controls.JMyButton btnback;
    private controls.JMyButton btnclear;
    private controls.JMyButton btndelete;
    private controls.JMyButton btnfind;
    private javax.swing.ButtonGroup btngroup;
    private controls.JMyButton btnsearch;
    private controls.JMyButton btnupdate;
    private controls.JMyCombBox cbxdept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdodept;
    private javax.swing.JRadioButton rdolocation;
    private javax.swing.JRadioButton rdoname;
    private javax.swing.JRadioButton rdonumber;
    private javax.swing.JTable tblproj;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtprojectname;
    private javax.swing.JTextField txtprojectno;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
