/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import campany.Tools;
import jaco.mp3.player.MP3Player;
import java.io.File;

import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author hp
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form frmTest
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        text = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMyButton1 = new controls.JMyButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        comb = new controls.JMyCombBox();

        jMenuItem1.setText("open");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("close");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text.setText("Text Department");
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMyButton1.setText("jMyButton1");
        jMyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Salary");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(272, 272, 272)
                        .addComponent(jRadioButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comb, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jMyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(comb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        Department dept = new Department();
       //dept.setDeptNo(1);
//        dept.setDeptName("IS and CS");
//        dept.setLocation("Cairo");
//        dept.add();
//        dept.setDeptNo(2);
//        dept.setDeptName("IS ");
//        dept.setLocation("Giza");
//        dept.add();
        //dept.getAllRows(table);
        
       // Tools.msgBox(dept.getAutoNumber());
       //dept.getCustomRows("select * from department", table);
       //dept.getOneRow(table);
       //Tools.msgBox(dept.getValueByName("IS"));
       Tools.msgBox(dept.getNameByValue("2"));
        
    }//GEN-LAST:event_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean confirm = Tools.confirmMsg("aaaaaaaaaaa?");
        if (confirm){
            Tools.msgBox("yes");
        }
        else {
            Tools.msgBox("Other");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isEmailExist(String email) throws SQLException {
   Connection dbConnection = null;
   String selectSQL = "SELECT USER_EMAIL FROM USER WHERE USER_EMAIL = ?";
   PreparedStatement preparedStatement = dbConnection.prepareStatement(selectSQL);
   preparedStatement.setString(1, email);
   ResultSet rs = preparedStatement.executeQuery(selectSQL);

   return rs.next();               
}
    
     public static final String song = "C:\\Users\\hp\\Documents\\NetBeansProjects111111111\\Campany\\welcome.mp3";
     MP3Player mp3 =new MP3Player(new File(song));
    
    private void jMyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            //db.go.createTable("CREATE TABLE DEPARTMENT (DEPTNO INT PRIMARY KEY,DEPTNAME VARCHAR(150) UNIQUE,LOCATION VARCHAR(100))", "myname");
            //db.go.createViews("CREATE VIEW DEPARTMENT_DATA AS SELECT DEPTNO AS 'DEPARTMENT_NO', DEPTNAME AS 'DEPARTMENT', LOCATION FROM DEPARTMENT", "myname");
        //if(jTextField1.getText().matches("^\\d+$")){ // check the number 
        //if(jTextField1.getText().matches("^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$")){
        //if(jTextField1.getText().matches("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$")){   
        //if(db.go.createDataBaseAndInformation("myname")){
        
        
//        (			# Start of group
//  (?=.*\d)		#   must contains one digit from 0-9
//  (?=.*[a-z])		#   must contains one lowercase characters
//  (?=.*[A-Z])		#   must contains one uppercase characters
//  (?=.*[@#$%])		#   must contains one special symbols in the list "@#$%"
//              .		#     match anything with previous condition checking
//                {6,20}	#        length at least 6 characters and maximum of 20	
//)			# End of group
        
        
        
        //if(jTextField1.getText().matches("((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})")){
        //if(jTextField1.getText().matches("[a-zA-Z][0-9|a-zA-Z|.|-|-|_]+@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$") && !jTextField1.getText().contains("+") && !jTextField1.getText().contains("..") && !jTextField1.getText().contains(".-") && !jTextField1.getText().contains("-.") && !jTextField1.getText().contains("._") && !jTextField1.getText().contains("_.") && !jTextField1.getText().contains("-_") && !jTextField1.getText().contains("_-") && !jTextField1.getText().contains("--") && !jTextField1.getText().contains("__") && jTextField1.getText().contains("@gmail.com")){
////            if (db.go.createDataBaseAndInformation("myname")){
//        String email = "a.b.abdalla305@gmail.com ";
//        email = email.replace(" ","");
//        if(db.go.IsValidEmail(jTextField1.getText())){
//            
//            Tools.msgBox("Yes...");
//        }
//        else {
//           
//            Tools.msgBox("No...");
//        }
        
//           
          //jTextField1.setText(btnsearch.getHeight() + " , "+ btnsearch.getWidth());
//        if (!txtpassword.getText().equals(txtRepassword.getText())){
//               Tools.msgBox("Check Your Password And Re-Password...");
//            }
       
           //if (jTextField1.getText().matches("[1][9][8-9][0-9][-][0-9][0-9][-][0-9][0-9]")){
//           if (jTextField1.getText().matches("[a-zA-Z][0-9|a-zA-Z|\\s]+")){
//                Tools.msgBox("Yes...\nwelcom");
//        }
//           else {
//               Tools.msgBox("Search Text must be in Rang [1980-1999] in special form e.g. (1985-02-15)");
//           }
          if (db.go.sendEmail("55269","a.b.abdalla305@gmail.com")){
              Tools.msgBox("Yes...");
          }
          else {
              Tools.msgBox("NO...");
          }
            //db.go.sendEmail("55262424","a.b.abdalla305@gmail.com");
        
//            Random r = new Random();
//            int Low = 100000;
//            int High = 999999;
//            int rondomMessage = r.nextInt(High-Low) + Low;
//            
////            int s = 100000 ; 
////            int i = 999999 ;
////            int r = s + (int)(Math.random()*i);
//            Tools.msgBox(rondomMessage+"");
////            
            
//            Tools.msgBox(jTextField1.getText());
//            if (comb.getSelectedItem()==null){
//                Tools.msgBox("Yes");
//            }
//            else{
//                Tools.msgBox("No");
//            }
             

              // Tools.tone();
             // mp3.play();

              //Tools.tone();
          
        } catch (Exception ex) {
            Tools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_jMyButton1ActionPerformed

    private void jTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1MouseReleased

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        // TODO add your handling code here:
        
          
    }//GEN-LAST:event_jTextField1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyCombBox comb;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private controls.JMyButton jMyButton1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table;
    private controls.JMyButton text;
    // End of variables declaration//GEN-END:variables
}
